# Generated by Django 2.1.7 on 2023-11-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A_POSITIVE'), ('A-', 'A_NEGATIVE'), ('B+', 'B_POSITIVE'), ('B-', 'B_NEGATIVE'), ('O+', 'O_POSITIVE'), ('O-', 'O_NEGATIVE'), ('AB+', 'AB_POSITIVE'), ('AB-', 'AB_NEGATIVE')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
