# Generated by Django 2.1.7 on 2023-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_auto_20231106_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(choices=[('A+', 'A_POSITIVE'), ('A-', 'A_NEGATIVE'), ('B+', 'B_POSITIVE'), ('B-', 'B_NEGATIVE'), ('O+', 'O_POSITIVE'), ('O-', 'O_NEGATIVE'), ('AB+', 'AB_POSITIVE'), ('AB-', 'AB_NEGATIVE')], max_length=5)),
                ('donor_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A_POSITIVE'), ('A-', 'A_NEGATIVE'), ('B+', 'B_POSITIVE'), ('B-', 'B_NEGATIVE'), ('O+', 'O_POSITIVE'), ('O-', 'O_NEGATIVE'), ('AB+', 'AB_POSITIVE'), ('AB-', 'AB_NEGATIVE')], max_length=5),
        ),
    ]
