# Generated by Django 2.1.7 on 2023-11-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_auto_20231106_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='units_donated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
